### ISSUE TITLE
TestInitEmptyIPv4Packet failing on fresh install

### ISSUE THREAD

**Issue by tweiand** [intel-go/yanff#108]
Greetings!

Can I please get a nudge in the right direction on how to diagnose this issue in “packet_test.go”? I am going through the code now, but, wanted to see if this was a common issue.

Configuration:
* OS - Ubuntu 16.10
* Go - 1.9.1 (installed from tarball)
* Compiler - gcc 6.2.0
* Real HW - MacBookPro13,3 (10.12.6, 16G29)
* Hypervisor - VMware Fusion 8.5.8 (yep, old)
* Ethernet - e1000e (82574L Gigabit Network Connection 10d3)
* Binding - IGB UIO
* GIT hash - e95c0bf399b9152b21e4cc9b81c11301631c60b7

How could a packet get changed during the “TestInitEmptyIPv4Packet” test? Logs below.

Thanks for any help!
-Timothy

========================================

[DPDK] vagrant@ubuntu-dpdk:~/go/src/github.com/intel-go/yanff$ sudo env PATH=$PATH make testing
Checking for AVX support... AVX and AVX2
make -C packet testing
make[1]: Entering directory '/home/vagrant/go/src/github.com/intel-go/yanff/packet'
Checking for AVX support... AVX and AVX2
go test
EAL: Detected lcore 0 as core 0 on socket 0
EAL: Detected lcore 1 as core 0 on socket 0
EAL: Detected lcore 2 as core 0 on socket 0
EAL: Detected lcore 3 as core 0 on socket 0
EAL: Support maximum 128 logical core(s) by configuration.
EAL: Detected 4 lcore(s)
EAL: Probing VFIO support...
EAL: Module /sys/module/vfio_pci not found! error 2 (No such file or directory)
EAL: VFIO modules not loaded, skipping VFIO support...
EAL: Module /sys/module/vfio_pci not found! error 2 (No such file or directory)
EAL: Setting up physically contiguous memory...
EAL: Trying to obtain current memory policy.
EAL: Hugepage /dev/hugepages/rtemap_1 is on socket 0
EAL: Hugepage /dev/hugepages/rtemap_0 is on socket 0
EAL: Ask a virtual area of 0x40000000 bytes
EAL: Virtual area found at 0x7fff00000000 (size = 0x40000000)
EAL: Ask a virtual area of 0x40000000 bytes
EAL: Virtual area found at 0x7ffe80000000 (size = 0x40000000)
EAL: Requesting 2 pages of size 1024MB from socket 0
EAL: TSC frequency is ~2903750 KHz
EAL: Master lcore 0 is ready (tid=f7fea8c0;cpuset=[0])
EAL: lcore 2 is ready (tid=ef7fe700;cpuset=[2])
EAL: lcore 3 is ready (tid=eeffd700;cpuset=[3])
EAL: lcore 1 is ready (tid=effff700;cpuset=[1])
EAL: PCI device 0000:03:00.0 on NUMA socket -1
EAL:   Invalid NUMA socket, default to 0
EAL:   probe driver: 8086:10d3 net_e1000_em
EAL:   Not managed by a supported kernel driver, skipped
EAL: PCI device 0000:0b:00.0 on NUMA socket -1
EAL:   Invalid NUMA socket, default to 0
EAL:   probe driver: 8086:10d3 net_e1000_em
EAL:   PCI memory mapped at 0x7fff40000000
EAL:   PCI memory mapped at 0x7fff40020000
EAL:   PCI memory mapped at 0x7fff40040000
PMD: eth_em_dev_init(): port_id 0 vendorID=0x8086 deviceID=0x10d3
--- FAIL: TestInitEmptyIPv4Packet (0.00s)
        packet_test.go:501: Incorrect result:
                got:  00000000000000000000000008004500001c00000000003b00007f00000180090905ffdd0000bbaa0000,
                want: 00000000000000000000000008004500001c00000000000000007f00000180090905ffdd0000bbaa0000

--- FAIL: TestInitEmptyIPv6Packet (0.00s)
        packet_test.go:526: Incorrect result:
                got:  00000000000000000000000086dd6000000000083b00dead000000000000000000000000beaf00000000000000000000000000000000ffdd0000bbaa0000,
                want: 00000000000000000000000086dd6000000000080000dead000000000000000000000000beaf00000000000000000000000000000000ffdd0000bbaa0000

FAIL
exit status 1
FAIL    github.com/intel-go/yanff/packet        0.605s
Makefile:10: recipe for target 'testing' failed
make[1]: *** [testing] Error 1
make[1]: Leaving directory '/home/vagrant/go/src/github.com/intel-go/yanff/packet'
Makefile:21: recipe for target 'packet' failed
make: *** [packet] Error 2

**Comment by mbulatova** [comment]
Since commit 8e54317c6 InitEmptyIPv4Packet and InitEmptyIPv6Packet also fill next proto field with 0x3b.
'Want' packets in test were not updated according to changes introduced in 8e54317c6.
Thanks for pointing to that.

**Comment by tweiand** [comment]
** happy dance for finding a bug **

Thanks for the fix! Will re-pull.
