### ISSUE TITLE
Wrong debug statistics: sent speed value differs from generator speed value

### ISSUE THREAD

**Issue by dkolistr** [intel-go/yanff#132]
I changed in low.c multiplier to 1, so it writes packets per second now, 
Current speed of fast generator 1 is 6212778 PKT/S, but sent 9229088 PKTs/s
It differs too much, I think its a bug. 

DEBUG: ---------------
DEBUG: System is using 6 cores now. 4 cores are left available.
DEBUG: Current speed of all receives: received 4440827 PKTs/s, pushed 4440827 PKTs/s
DEBUG: Current speed of all sends: required 9298656 PKTs/s, sent 9298656 PKTs/s
DEBUG: Current speed of stop ring: freed 4440922 PKTs/s
DEBUG: Number of packets in queue for handle:  0
DEBUG: Current speed of handler 4 is 2961944 PKT/S
DEBUG: Current speed of fast generator 1 is 6201237 PKT/S, target speed is 6000000 PKT/S
DEBUG: Mempool N 0 used 575 from 32764
DEBUG: Mempool N 1 used 262 from 32764
DEBUG: ---------------
DEBUG: System is using 6 cores now. 4 cores are left available.
DEBUG: Current speed of all receives: received 4437748 PKTs/s, pushed 4437748 PKTs/s
DEBUG: Current speed of all sends: required 9254240 PKTs/s, sent 9254240 PKTs/s
DEBUG: Current speed of stop ring: freed 4437869 PKTs/s
DEBUG: Number of packets in queue for handle:  0
DEBUG: Current speed of handler 4 is 2959896 PKT/S
DEBUG: Current speed of fast generator 1 is 6199040 PKT/S, target speed is 6000000 PKT/S
DEBUG: Mempool N 0 used 575 from 32764
DEBUG: Mempool N 1 used 121 from 32764
DEBUG: ---------------
DEBUG: System is using 6 cores now. 4 cores are left available.
DEBUG: Current speed of all receives: received 8907874 PKTs/s, pushed 8907874 PKTs/s
DEBUG: Current speed of all sends: required 18626432 PKTs/s, sent 18626432 PKTs/s
DEBUG: Current speed of stop ring: freed 8907763 PKTs/s
DEBUG: Number of packets in queue for handle:  46
DEBUG: Current speed of handler 4 is 2965938 PKT/S
DEBUG: Current speed of fast generator 1 is 6201941 PKT/S, target speed is 6000000 PKT/S
DEBUG: Mempool N 0 used 575 from 32764
DEBUG: Mempool N 1 used 518 from 32764
DEBUG: ---------------
DEBUG: System is using 6 cores now. 4 cores are left available.
DEBUG: Current speed of all receives: received 4411869 PKTs/s, pushed 4411869 PKTs/s
DEBUG: Current speed of all sends: required 9229088 PKTs/s, sent 9229088 PKTs/s
DEBUG: Current speed of stop ring: freed 4412054 PKTs/s
DEBUG: Number of packets in queue for handle:  0
DEBUG: Current speed of handler 4 is 2970708 PKT/S
DEBUG: Current speed of fast generator 1 is 6212778 PKT/S, target speed is 6000000 PKT/S
DEBUG: Mempool N 0 used 575 from 32764
DEBUG: Mempool N 1 used 176 from 32764

**Comment by ifilippov** [comment]
Done.
