### ISSUE TITLE
Broken mailing list link

### ISSUE THREAD

**Issue by HarrisonATT** [intel-go/yanff#15]
On the [CONTRIBUTING.md](https://github.com/intel-go/yanff/blob/master/CONTRIBUTING.md#user-content-issue-tracking) page, it claims that the [mailing list](https://lists.clearlinux.org/mailman/listinfo/YANFF-devel) is a "durable communication channel", but the link is broken. I wasn't able to find a live link to any mailing list for YANFF.

I tried the IRC channel but either I didn't do it right (I've never used IRC before) or nobody was on when I tried.

**Comment by aregm** [comment]
Link is fixed.
