### ISSUE TITLE
Go vet: possible misuse of unsafe.Pointer

### ISSUE THREAD

**Issue by Quasilyte** [intel-go/yanff#67]
**Problem**: many (by measures of "awesome-go") `go vet` warnings.

There are many `integer to pointer` casts rule triggers in `go vet` report for Yanff.

Most (all?) cases go from `pointer`->`uintptr`->`pointer`, so it should not be unsafe as lint
assumes (it references [Go 1.3a changes to GC](https://golang.org/doc/go1.3a)).

What do you think about these solutions ("workarounds", actually):

1. Add more methods like `unparsed`, which return `unsafe.Pointer` with offset calculations applied, without additional type cast to `uintptr`. This way, 3-level casts will go away and related lint warnings will go avay. 
Note: `go vet` allows this constructions: `unsafe.Pointer(uintptr(p) + offset)`.

2. Move this kind of data casts (maywith struct itself) in separate package. Go can do cross-package inlining, so no performance will be lost, right? Report on Yanff will increase.

Related to [adding YANFF to awesome-go](https://github.com/avelino/awesome-go/pull/1579#pullrequestreview-61838972).

**Comment by aregm** [comment]
This is a feature of the project and not a flaw or some mistake. We are using unsafe memory to manipulate C memory from Go, modifying what pointer refers to without copying for performance reasons. It cannot be done without copying and any other method also implies some copy. We know exactly what we are doing. And go_vet is kind of recommendation and not a rule. So if go_vet is a stopper for being included - fine.

**Comment by mbulatova** [comment]
Iskander's suggestion makes Go vet much more happy: for packet/packet.go it gives only one warning:
packet\packet.go:355: possible misuse of unsafe.Pointer

https://github.com/intel-go/yanff/commit/1d70bd23b30a7dc5f057d75a1df6168f9037ab17

**Comment by Quasilyte** [comment]
Leaving [proposal 20171](https://github.com/golang/go/issues/20171) link for the reference.
> proposal: spec: disallow T<->uintptr conversion for type T unsafe.Pointer

Deeper investigation is needed, but at a first glance it seems if this ever accepted, `yanff` code will break.

**Comment by TocarIP** [comment]
proposal 20171  is  about  type aliases/other stuff that hides  unsafe.Pointer. I don;t think YANFF uses type aliases, so it shouldn't be affected

**Comment by Quasilyte** [comment]
@TocarIP, seems like you are right.
But in this case, [#20171](https://github.com/golang/go/issues/20171) looks awfully confusing.

**Comment by mbulatova** [comment]
Suggestion is accepted, fixed in #150
